version: '3.8'

services:
  web:
    build: ./nginx
    container_name: web
    restart: always
    ports:
      - 80:80
  bd:
    build: ./base
    container_name: bd
    restart: always
    environment:
      POSTGRES_DB: root
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./.databases/docker-postgres-init.sql:/docker-entrypoint-initdb.d/docker-postgres-init.sql
    ports:
      - 5432:5432
  api:
    build: ./api
    container_name: api
    ports:
      - 4000
  adminer:
    build: ./adminer
    container_name: adminer
    restart: always
    ports:
      - 9000:9000
